# Generated by Django 5.0.1 on 2026-01-07 10:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submission_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("python", "Python"),
                            ("java", "Java"),
                            ("javascript", "JavaScript"),
                            ("cpp", "C++"),
                            ("c", "C"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "code_file",
                    models.FileField(
                        upload_to="submissions/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "py",
                                    "java",
                                    "js",
                                    "cpp",
                                    "c",
                                    "txt",
                                ]
                            )
                        ],
                    ),
                ),
                ("code_text", models.TextField(blank=True, null=True)),
                ("file_size", models.IntegerField(default=0)),
                ("line_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_temporary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "code_submissions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComparisonRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "comparison_type",
                    models.CharField(
                        choices=[
                            ("single_vs_repo", "Single File vs Repository"),
                            ("file_vs_file", "File vs File"),
                            (
                                "multiple_vs_multiple",
                                "Multiple Files vs Multiple Files",
                            ),
                            ("text_vs_text", "Text vs Text"),
                        ],
                        max_length=30,
                    ),
                ),
                ("similarity_threshold", models.FloatField(default=0.75)),
                ("use_ml_analysis", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source_submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_comparisons",
                        to="users.codesubmission",
                    ),
                ),
                (
                    "target_submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_comparisons",
                        to="users.codesubmission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "comparison_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SimilarityResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("overall_similarity_score", models.FloatField()),
                ("structural_similarity", models.FloatField(default=0.0)),
                ("token_similarity", models.FloatField(default=0.0)),
                ("ast_similarity", models.FloatField(default=0.0)),
                (
                    "ml_similarity",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                ("identical_segments", models.JSONField(default=list)),
                ("near_identical_segments", models.JSONField(default=list)),
                ("code_metrics", models.JSONField(default=dict)),
                ("visualization_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comparison",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="users.comparisonrequest",
                    ),
                ),
            ],
            options={
                "db_table": "similarity_results",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_favorite", models.BooleanField(default=False)),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comparison",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.comparisonrequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_comparisons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.similarityresult",
                    ),
                ),
            ],
            options={
                "db_table": "saved_comparisons",
                "ordering": ["-saved_at"],
                "unique_together": {("user", "comparison")},
            },
        ),
    ]
