# Generated by Django 5.0.1 on 2026-01-07 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cyclomatic_complexity", models.FloatField(default=0.0)),
                ("maintainability_index", models.FloatField(default=0.0)),
                ("lines_of_code", models.IntegerField(default=0)),
                ("logical_lines", models.IntegerField(default=0)),
                ("comment_lines", models.IntegerField(default=0)),
                ("blank_lines", models.IntegerField(default=0)),
                ("halstead_volume", models.FloatField(default=0.0)),
                ("halstead_difficulty", models.FloatField(default=0.0)),
                ("unique_operators", models.IntegerField(default=0)),
                ("unique_operands", models.IntegerField(default=0)),
                ("function_count", models.IntegerField(default=0)),
                ("class_count", models.IntegerField(default=0)),
                ("ast_node_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="users.codesubmission",
                    ),
                ),
            ],
            options={
                "db_table": "code_metrics",
            },
        ),
    ]
