# Generated by Django 5.0.1 on 2026-01-07 10:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("user_management", "User Management"),
                            ("dataset_management", "Dataset Management"),
                            ("model_management", "Model Management"),
                            ("system_config", "System Configuration"),
                            ("report_generation", "Report Generation"),
                        ],
                        max_length=30,
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "affected_object",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Admin Activities",
                "db_table": "admin_activities",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="CodeDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dataset_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField()),
                (
                    "dataset_type",
                    models.CharField(
                        choices=[
                            ("training", "Training Dataset"),
                            ("validation", "Validation Dataset"),
                            ("reference", "Reference Repository"),
                            ("benchmark", "Benchmark Dataset"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("python", "Python"),
                            ("java", "Java"),
                            ("javascript", "JavaScript"),
                            ("cpp", "C++"),
                            ("c", "C"),
                            ("multi", "Multi-Language"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "file_path",
                    models.FileField(blank=True, null=True, upload_to="datasets/"),
                ),
                ("external_url", models.URLField(blank=True, null=True)),
                ("file_count", models.IntegerField(default=0)),
                ("total_size", models.BigIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_processed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "code_datasets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("random_forest", "Random Forest"),
                            ("neural_network", "Neural Network"),
                            ("svm", "Support Vector Machine"),
                            ("gradient_boosting", "Gradient Boosting"),
                            ("ensemble", "Ensemble Model"),
                        ],
                        max_length=30,
                    ),
                ),
                ("version", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("model_file", models.FileField(upload_to="ml_models/")),
                ("accuracy", models.FloatField(default=0.0)),
                ("precision", models.FloatField(default=0.0)),
                ("recall", models.FloatField(default=0.0)),
                ("f1_score", models.FloatField(default=0.0)),
                ("training_params", models.JSONField(default=dict)),
                ("feature_importance", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("training", "Training"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        default="inactive",
                        max_length=20,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("trained_at", models.DateTimeField(auto_now_add=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("usage_count", models.IntegerField(default=0)),
                (
                    "trained_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "training_dataset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trained_models",
                        to="admins.codedataset",
                    ),
                ),
            ],
            options={
                "db_table": "ml_models",
                "ordering": ["-trained_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("error", "Error"),
                            ("warning", "Warning"),
                            ("info", "Information"),
                            ("success", "Success"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "system_alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("config_key", models.CharField(max_length=100, unique=True)),
                ("config_value", models.TextField()),
                ("description", models.TextField()),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("float", "Float"),
                            ("boolean", "Boolean"),
                            ("json", "JSON"),
                        ],
                        default="string",
                        max_length=20,
                    ),
                ),
                ("is_editable", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "system_configurations",
            },
        ),
    ]
