# Generated by Django 5.0.1 on 2026-01-07 10:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AggregateReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("user_activity", "User Activity Report"),
                            ("similarity_trends", "Similarity Trends"),
                            ("plagiarism_incidents", "Plagiarism Incidents"),
                            ("system_usage", "System Usage Statistics"),
                            ("model_performance", "Model Performance"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("file_path", models.FileField(upload_to="aggregate_reports/%Y/%m/")),
                ("data_summary", models.JSONField(default=dict)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "aggregate_reports",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="SimilarityReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "report_format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("csv", "CSV"),
                            ("json", "JSON"),
                            ("html", "HTML"),
                        ],
                        max_length=10,
                    ),
                ),
                ("file_path", models.FileField(upload_to="reports/%Y/%m/%d/")),
                ("file_size", models.IntegerField(default=0)),
                ("include_visualizations", models.BooleanField(default=True)),
                ("include_code_segments", models.BooleanField(default=True)),
                ("include_metrics", models.BooleanField(default=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("download_count", models.IntegerField(default=0)),
                ("last_downloaded", models.DateTimeField(blank=True, null=True)),
                (
                    "comparison",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.comparisonrequest",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.similarityresult",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "similarity_reports",
                "ordering": ["-generated_at"],
            },
        ),
    ]
